name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the docker image
        run: docker build . --file Dockerfile.dev --tag d4sf/docker-react-test
    
      - uses: actions/checkout@v4
      - name: Run image and tests
        run: docker run -e CI=true d4sf/docker-react-test npm test